### PR TITLE
paper-comparison vignette

### LINKED ISSUE #120: paper-comparison vignette comments
* download necessary external files
  - The `paper-comparison` vignette starts by loading in R data files, but this assumes that the code is being run from within the project folder that has been cloned or downloaded from GitHub. 
I don't think this will work for folks who are installing from GitHub or from CRAN. These lines can be modified to download the necessary files from e.g. GitHub.

* check package dependencies
  - sourcing the downloaded scripts will try to load some packages. These should be added to the `suggests` field of `DESCRIPTION`

### PR DESCRIPTION
**Pull request by ha0ye**
Summary of changes:
* no longer rely on files in the vignettes folder (i.e. the ~150MB `christensenetal-comparison-files` folder)
  - instead, download files from Erica's repo, the PortalData repo, and a separate [replication repo](https://github.com/weecology/portal-extreme-events-LDATS-replication)
* use a single control parameter to dictate whether to run the models or not
  - this is a rmarkdown parameter set in the yaml header
  - by default, it is set to false, and so does not run the LDA or TS models, instead downloading them
  - when set to true, it foregoes downloading the model objects, and runs all the LDA and TS models
* consolidate duplicated code
  - for handling the various outputs from running the LDA model, running the TS model, selecting the best LDA and TS model, and getting the dates
* make the changepoint results consistent objects
  - save the whole posterior distributions for the changepoints (which simplifies follow-up analyses)
* some general cleanup of code chunks, section headers, etc.

closes #120

### CODE REVIEW

**Comment by juniperlsimonis** [comment]
are the build breaks here the random number thingy?

**Comment by ha0ye** [comment]
For the last commit, yes. (I haven’t looked at the logs for all prior commits).

**Comment by juniperlsimonis** [comment]
finally got back to this (sorry!) and with rebasing this branch with the updates you had in the other pr, @ha0ye it looks like that takes care of the test issue (woo hoo!), which was my concern here.
@diazrenata do you have any editing feedback or can this be merged in?

**Comment by juniperlsimonis** [comment]
do note that we'll need to update some of the code and model objects with the jump to v0.2.0 (ref: #131 ), so i'm not sure which we want to do first?

**Comment by ha0ye** [comment]
> do note that we'll need to update some of the code and model objects with the jump to v0.2.0 (ref: #131 ), so i'm not sure which we want to do first?

I think this PR is independent enough (it only changes 2 files) that it can be rebased on top of 0.2.0; and the vignette should be restructured to make the changes to the code and model straightforward in terms of a patch or a few additional commits.

**Comment by juniperlsimonis** [comment]
that makes sense. the thing we'll definitely need to keep an eye out for though is updated model output structure that updated code is pointed to (the `timename` element in the `TS` output in particular), as we'll need to update model objects wherever they live. i've updated the model objects in the v0.2.0 branch, so the ones you are calling up remotely here can get updated from those ones, yeah?

> 
> 
> > do note that we'll need to update some of the code and model objects with the jump to v0.2.0 (ref: #131 ), so i'm not sure which we want to do first?
> 
> I think this PR is independent enough (it only changes 2 files) that it can be rebased on top of 0.2.0; and the vignette should be restructured to make the changes to the code and model straightforward in terms of a patch or a few additional commits.

**Pull request merged**
